# Generated by Django 2.2.12 on 2022-11-25 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='jenis_id',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='link_gbr',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='waktu_posting',
        ),
        migrations.AddField(
            model_name='barang',
            name='tipe_brg',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='subscribe',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
